# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FFrrgvm27C7JErvAsf0FPWbAcWOYPtYl
"""

import numpy as np
import cv2
import cvzone
from tracker import *
import time
import pyrebase
import logging
from tuya_connector import TuyaOpenAPI, TUYA_LOGGER

# ยืนยันตัวตน Firebase เพิ่อดึง API ของ Realtime Database

# ALL THIS KEY HAVE NO LONGER AVAILABLE.
config = {
    "apiKey": "AIzaSyC9t5ppjAWpulEhz8E4S6pUD7ceNhLBQ_g",
    "authDomain": "webapp-b33f6.firebaseapp.com",
    "databaseURL": "https://webapp-b33f6-default-rtdb.asia-southeast1.firebasedatabase.app",
    "projectId": "webapp-b33f6",
    "storageBucket": "webapp-b33f6.appspot.com",
    "messagingSenderId": "917044709858",
    "appId": "1:917044709858:web:2067945324507074e811bb",
    "measurementId": "G-P458HC4P1W",
}
# ดึงฟีเจอร์ Realtime Database จาก Firebase
firebase = pyrebase.initialize_app(config)
db = firebase.database()
# ประกาศตัวแปรไว้เก็บค่าที่ดึงมาจาก Firebase Realime Database
list_ref = db.child("number_people").get("people_list").val()
list_c = str(list_ref["people_list"])
time_c = str(list_ref["time_list"])
# แปลงค่าตัวแปรที่เก็บข้อมูลจำนวนการเข้าออกล่าสุดและ timestamp การเข้าออกเป็น python list
people_list = []
time_list = []
for i in list_c.split(","):
    people_list.append(i)
# 53
for j in time_c.split(","):
    time_list.append(j)
# ยืนยันตัวตน TuyaAPI เพื่อดึง API ควบคุมการทำงานของ Smart Switch
ACCESS_ID = "xhyswgra7ppfa85ksyxe"
ACCESS_KEY = "0abb93025b15443e98d1bc8ca7fa3d6d"
API_ENDPOINT = "https://openapi.tuyaus.com"
DEVICE_ID = "eb61683cc6099a9009cxp8"
# ดึง API ของ Tuya
openapi = TuyaOpenAPI(API_ENDPOINT, ACCESS_ID, ACCESS_KEY)
openapi.connect()


# ฟังก์ชันแสดงตำแหน่ง pointer ของ openCV ในส่วน output window
def RGB(event, x, y, flags, param):
    if event == cv2.EVENT_MOUSEMOVE:
        point = [x, y]
        print(point)


# ดึง datasets ที่เก็บชื่อของ Object ที่จะทำการ detect
my_file = open("coco.txt", "r")
data = my_file.read()
class_list = data.split("\n")

# ดึงโมเดล mobilenetSSD
prototxt = "MobileNetSSD.prototxt"
caffe_model = "MobileNetSSD.caffemodel"
net = cv2.dnn.readNetFromCaffe(prototxt, caffe_model)

# Object พื้นฐานที่อยู่ในโมเดล MobilenetSSD
classNames = [
    "BACKGROUND",
    "AEROPLANE",
    "BICYCLE",
    "BIRD",
    "BOAT",
    "BOTTLE",
    "BUS",
    "CAR",
    "CAT",
    "CHAIR",
    "COW",
    "DININGTABLE",
    "DOG",
    "HORSE",
    "MOTORBIKE",
    "PERSON",
    "POTTEDPLANT",
    "SHEEP",
    "SOFA",
    "TRAIN",
    "TVMONITOR",
]
# ดึงภาพจาก Webcam
cap = cv2.VideoCapture(0)

# กำหนดตำแหน่ง Area ที่จะกำหนดการเข้าออกของ Object
area1 = [(163, 185), (928, 135), (880, 886), (298, 1026)]
# 54
area2 = [
    (49, 1451),
    (929, 1015),
    (971, 94),
    (1429, 60),
    (1438, 1261),
    (53, 1829),
]
# ประกาศตัวแปรที่ต้องเก็บค่าเพื่อคำนวณหาจำนวนคนเข้าออก
pre_state = None
count = 0
going_out = {}
going_in = {}
ppl = 0
counter1 = []
counter2 = []
out_c = len(counter1)
in_c = len(counter2)

# ดึงอัลกอริทึม Centroid tracker
tracker = Tracker()
r_bbox_idx = []
# เริ่มลูป OpenCV, ดึงภาพจาก Webcam ,ประมวลผลภาพที่ได้จาก Webcam เพื่อหาคนในรูป ,วาดกรอบรอบๆคน
# และติดตามการเคลื่อนที่
while True:
    ret, frame = cap.read()
    list = []
    width = frame.shape[1]
    height = frame.shape[0]
    blob = cv2.dnn.blobFromImage(
        frame,
        scalefactor=1 / 127.5,
        size=(300, 300),
        mean=(127.5, 127.5, 127.5),
        swapRB=True,
        crop=False,
    )
    net.setInput(blob)
    detections = net.forward()
    for i in np.arange(0, detections.shape[2]):
        confidence = detections[0, 0, i, 2]
        x3 = int(detections[0, 0, i, 3] * width)
        y3 = int(detections[0, 0, i, 4] * height)
        x4 = int(detections[0, 0, i, 5] * width)
        y4 = int(detections[0, 0, i, 6] * height)
        # 55
        cx = int(x3 + x4) // 2
        cy = int(y3 + y4) // 2
        class_id = int(detections[0, 0, i, 1])
        if confidence > 0.03 and classNames[class_id] == "PERSON":
            list.append([x3, y3, x4, y4])
    class_id = int(detections[0, 0, i, 1])
    bbox_idx = tracker.update(list)
    for bbox in bbox_idx:
        x3, y3, x4, y4, id = bbox
        cx = int(x3 + x4) // 2
        cy = int(y3 + y4) // 2
        bbox.append(cx)
        bbox.append(cy)
        cvzone.putTextRect(frame, f'{id}', (cx, cy), 2, 2)
        timestamp = time.strftime('%H:%M')
        out_c = len(counter1)
        in_c = len(counter2)
        person = in_c - out_c
        # ส่วนการทำงานของการเข้าห้อง
        result = cv2.pointPolygonTest(np.array(area2, np.int32), ((cx, cy)), False)
        if result >= 0:
            going_out[id] = (cx, cy)
        if id in going_out:
            result1 = cv2.pointPolygonTest(
                np.array(area1, np.int32), ((cx, cy)), False
            )
            if result1 >= 0:
                cv2.circle(frame, (cx, cy), 7, (255, 0, 255), -1)
                if counter1.count(id) == 0:
                    counter1.append(id)
                    time_list.pop(0)
                    time_list.append(timestamp + " น.")
                    # 56
                    time_c = ",".join(time_list)
                    out_c = len(counter1)
                    person = in_c - out_c
                    people_list.pop(0)
                    people_list.append(str(person))
                    list_c = ",".join(people_list)
                    print("id :", id, "IN at", timestamp)
        # ส่วนการทำงานของการออกจากห้อง
        result2 = cv2.pointPolygonTest(np.array(area1, np.int32), ((cx, cy)), False)
        if result2 >= 0:
            going_in[id] = (cx, cy)
        if id in going_in:
            result3 = cv2.pointPolygonTest(
                np.array(area2, np.int32), ((cx, cy)), False
            )
            if result3 >= 0:
                print(counter2)
                cv2.circle(frame, (cx, cy), 7, (0, 255, 0), -1)
                if counter2.count(id) == 0:
                    counter2.append(id)
                    time_list.pop(0)
                    time_list.append(timestamp + "น.")
                    time_c = ",".join(time_list)
                    in_c = len(counter2)
                    person = in_c - out_c
                    people_list.pop(0)
                    people_list.append(str(person))
                    print(list_c)
                    list_c = ",".join(people_list)
                    print("id :", id, "OUT at", timestamp)
    person = in_c - out_c
    # วาดกรอบ Area การกำหนดการเข้าออกลงไปใน output window
    # 57
    cv2.polylines(frame, [np.array(area1, np.int32)], True, (0, 255, 0), 2)
    cv2.polylines(frame, [np.array(area2, np.int32)], True, (0, 0, 255), 2)
    # แสดงจำนวนการเข้า, ออก, จำนวนคนในห้อง
    cvzone.putTextRect(frame, f'OUT : {out_c}', (400, 60), 2, 2)
    cvzone.putTextRect(frame, f'IN : {in_c}', (460, 160), 2, 2)
    cvzone.putTextRect(frame, f'INSIDE : {person}', (460, 240), 2, 2)
    # ปรับหน้าต่างให้สามารถยืดหดได้ ,แสดง output window, แสดงตำแหน่ง pointer บน output window
    cv2.namedWindow("frame", cv2.WINDOW_NORMAL)
    cv2.imshow("frame", frame)
    cv2.setMouseCallback('frame', RGB)
    # อัพเดตค่าต่างๆลงไปใน Firebase Realtime Database
    data = {
        "number_people_in": in_c,
        "number_people_out": out_c,
        "number_people_inside": person,
        "people_list": list_c,
        "time_list": time_c,
    }
    db.child("number_people").update(data)

    # ส่วนของการกำหนดการทำงานของ Smart switch
    if state != pre_state:
        pre_state = state
        if state == "on":
            commands = {'commands': [{'code': 'switch_1', 'value': True}]}
            openapi.post(
                '/v1.0/iot-03/devices/{}/commands'.format(DEVICE_ID), commands
            )
            db.child("number_people").update(data)
        elif state == "off":
            commands = {'commands': [{'code': 'switch_1', 'value': False}]}
            openapi.post(
                '/v1.0/iot-03/devices/{}/commands'.format(DEVICE_ID), commands
            )
    if person > 0:
        state = "on"
        statusState = True
        TimeDelay = time.time()
    elif statusState and person < 1 and time.time() - TimeDelay >= 5:
        state = "off"
        # 58
        statusState = False
    elif not (statusState):
        state = "off"
        statusState = False
    if state != pre_state:
        pre_state = state
        if state == "on":
            commands = {'commands': [{'code': 'switch_1', 'value': True}]}
            openapi.post(
                '/v1.0/iot-03/devices/{}/commands'.format(DEVICE_ID), commands
            )
            db.child("number_people").update(data)
        elif state == "off":
            commands = {'commands': [{'code': 'switch_1', 'value': False}]}
            openapi.post(
                '/v1.0/iot-03/devices/{}/commands'.format(DEVICE_ID), commands
            )
    # ดักการกดคีย์ Esc เพื่อยุติการทำงานทั้งหมด
    if cv2.waitKey(1) & 0xFF == 27:
        break
# ส่วนของการปิดหน้าต่าง output window
cap.release()
cv2.destroyAllWindows()